sexos=(('Femenino','Femenino'),('Masculino','Masculino'))
estado_civil=(('Casado','Casado'),('Soltero','Soltero'),('Divorciado','Divorciado'))
tipo_sangre = (('-A','-A'),('B','B'),('O','O'),('ABO','ABO'))
area = (('Radiologia','Radiologia'),('Rayos X','Rayos X'),('Tomografia','Tomografia'))
especialidades =(('Neurologia','Neurologia'),('Neurocirujia','Neurocirujia'))