# Generated by Django 3.2.9 on 2021-11-24 00:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReservarCita', '0020_auto_20211123_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('ruta', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Resonancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resultados.recurso')),
                ('tecnologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.tecnologo')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('Diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resultados.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.cita')),
                ('resonancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resultados.resonancia')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resultados.recurso')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resultados.imagen'),
        ),
    ]
