# Generated by Django 3.2.2 on 2021-12-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resultados', '0002_auto_20211125_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='ruta',
        ),
        migrations.AddField(
            model_name='recurso',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Resultados/images'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
