# Generated by Django 3.2.2 on 2021-12-07 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resultados', '0003_auto_20211207_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='resonancia',
            name='recurso',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='resonancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resultados.resonancia'),
        ),
        migrations.AddField(
            model_name='resonancia',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resonancia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='resonancia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Resultados/images'),
        ),
        migrations.AddField(
            model_name='resonancia',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
