# Generated by Django 3.2.9 on 2021-11-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=12, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Divorciado', 'Divorciado')], max_length=20, verbose_name='Ingrese su estado civil')),
            ],
        ),
    ]
