# Generated by Django 3.2.9 on 2021-11-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0002_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.AddField(
            model_name='medico',
            name='persona',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ReservarCita.persona'),
            preserve_default=False,
        ),
    ]
