# Generated by Django 3.2.9 on 2021-11-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0003_auto_20211121_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ReservarCita.persona')),
                ('id_seguro', models.IntegerField(max_length=12)),
            ],
        ),
    ]
