# Generated by Django 3.2.9 on 2021-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0004_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_seguro',
            field=models.IntegerField(default=0),
        ),
    ]
