# Generated by Django 3.2.9 on 2021-11-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0006_paciente_tipo_sangre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologo',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ReservarCita.persona')),
                ('area', models.CharField(choices=[('Radiologia', 'Radiologia'), ('Rayos X', 'Rayos X'), ('Tomografia', 'Tomografia')], default='Radiologia', max_length=12)),
            ],
        ),
    ]
