# Generated by Django 3.2.9 on 2021-11-22 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0008_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=datetime.time),
        ),
    ]
