# Generated by Django 3.2.9 on 2021-11-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0009_cita_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='confirmacion',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.medico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='tecnologo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.tecnologo'),
            preserve_default=False,
        ),
    ]
