# Generated by Django 3.2.9 on 2021-11-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0010_auto_20211122_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigo_especialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Neurologia', 'Neurologia'), ('Neurocirujia', 'Neurocirujia')], default='Neurologia', max_length=25)),
            ],
        ),
    ]
