# Generated by Django 3.2.9 on 2021-11-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0011_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ReservarCita.especialidad'),
        ),
    ]
