# Generated by Django 3.2.9 on 2021-11-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0012_medico_especialidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
    ]
