# Generated by Django 3.2.9 on 2021-11-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0013_alter_especialidad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(default=' ', max_length=50, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Divorciado', 'Divorciado')], max_length=20, verbose_name='Estado civil'),
        ),
    ]
