# Generated by Django 3.2.9 on 2021-11-23 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0014_auto_20211122_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.IntegerField(default=934776248),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='', max_length=100, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=73118828),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
