# Generated by Django 3.2.9 on 2021-11-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0015_auto_20211122_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=35, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=73118828, verbose_name='DNI'),
        ),
    ]
