# Generated by Django 3.2.9 on 2021-11-23 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0016_auto_20211122_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.CharField(default='', max_length=8, primary_key=True, serialize=False, verbose_name='Código del turno')),
                ('hora_inicio', models.TimeField(default=datetime.time, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(default=datetime.time, verbose_name='Hora de termino')),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de nacimiento'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default=datetime.time, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(default=datetime.time, verbose_name='Hora de termino')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.turno')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.horario'),
        ),
    ]
