# Generated by Django 3.2.9 on 2021-11-23 23:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0019_auto_20211123_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operacion', models.IntegerField(default=0, verbose_name='Código de operación')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.sede'),
        ),
        migrations.AddField(
            model_name='cita',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.transaccion'),
        ),
    ]
