# Generated by Django 2.2.4 on 2021-11-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0021_auto_20211125_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.Medico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tecnologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservarCita.Tecnologo'),
        ),
    ]
