# Generated by Django 2.2.4 on 2021-12-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservarCita', '0022_auto_20211125_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
    ]
